print("Cuantos años tienes?", end=' ')
age = input()
print("Cuanto mides?", end=' ')
height = input()
print("Cuanto pesas?", end=' ')
weight = input()
print(f"Entonces tienes {age} años, estatura, {height} y pesas {weight} Kg.")
